### ISSUE TITLE
Back End:Jake or Matt will finish getting accounts to auto generate with new user

### ISSUE THREAD

**Issue by jake-brennan714** [Morgan-MoneyApp/MoneyManagementApp#42]
- [x] Accounts generate automatically
- [x] Account numbers generate sequentially
- [ ] Deal with fake data
- [ ] Do binary search algo to find _highest used account number_

**Comment by jake-brennan714** [comment]
#41 Tasks 1 and 2
